### ISSUE TITLE
When new dataset is created, manage pipeline does not appear there and user is force to create CKAN resources

### ISSUE THREAD

**Issue by tomas-knap** [OpenDataNode/ckanext-odn-pipeline#1]
When creating new dataset record in ODN/ic manually (typical workflow), I click add dataset, fill the metadata and then:

1) I am forced to fill at least one resource, which is wrong. Solution: Data publisher must not be forced to specify CKAN resource. 

![screen shot 2014-12-11 at 10 08 52](https://cloud.githubusercontent.com/assets/3014917/5391642/ca545dc2-811d-11e4-81d3-76518553cfd0.png)

2) there is no way how to directly associate pipeline with the newly created dataset - one has to save the datasets, click manage and then he can associated the pipeline. Solution: The pipelines tab must be avalable when new dataset record is created.

**Comment by mvi-eea-sk** [comment]
https://github.com/OpenDataNode/odn-ckan/commit/479f1313be4b46524075f208944fa87481c3b136
fixed in odn-ckan
