### ISSUE TITLE
Not associated pipeline not in list of pipelines when was previously associated

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/ckanext-odn-pipeline#12]
Based on OpenDataNode/open-data-node#116

associated new pipeline to dataset. I configured it manually.
Then I disassociated this pipeline.
Consequently I wanted associate new existing pipeline to this dataset. 
BUT in offered pipelines this one was missing.

**Comment by skrchnavy** [comment]
as reported in OpenDataNode/open-data-node#116 it was partialy fixed in v1.0.2 but proper fix is expected in v1.0.3

**Comment by skrchnavy** [comment]
fix moved to 1.1.0

**Comment by skrchnavy** [comment]
@mvi-eea-sk: you have mentioned in  OpenDataNode/open-data-node#116 that this is fixed in 1.0.2 and proper fix is in 1.0.3, Is it correct, can we close this issue as solved?

**Comment by mvi-eea-sk** [comment]
@skrchnavy: in progress

**Comment by skrchnavy** [comment]
Planed to be finalized in v1.1.2

**Comment by mvi-eea-sk** [comment]
actually this should be fixed already in v1.1.0, can you test it?

**Comment by skrchnavy** [comment]
@mvi-eea-sk is there any commit available for reference?

**Comment by mvi-eea-sk** [comment]
@skrchnavy https://github.com/OpenDataNode/ckanext-odn-cas/commit/a9b8b200d13e2c019520f8ad940a5d9ebdedb815
so definitely ODN_v1.1.0
