### ISSUE TITLE
List of scheduling rules for a pipeline associated with dataset 

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/ckanext-odn-pipeline#2]
When 'Schedule' is chosen from combo box in the list of associated pipelines in IC, Scheduler in UV is opened. The list of scheduling rules should contain only scheduling rules created for the pipeline selected in IC not all existing scheduling rules.

**Comment by skrchnavy** [comment]
related to  OpenDataNode/open-data-node#113
depends on UnifiedViews/Core#384

**Comment by skrchnavy** [comment]
UnifiedViews/Core#384 planed for UV 2.2.0 so when finalized it can be used

**Comment by mvi-eea-sk** [comment]
@skrchnavy this isn't solved... on UV side it was implemented, but you can't open from extension  the "new" scheduler URL yet.
