### ISSUE TITLE
Two pipelines with identical names in the list of pipelines

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/ckanext-odn-pipeline#3]
To create a new associated pipeline for a dataset in IC choose 'Create new manually'. Fill the name of the pipeline with an existing name of already created pipeline. Press Finish button. Perform some action (e.g. choose a DPU) to make saving possible. Save the pipeline. Error message is displayed (pipeline with this name already exists). Close the message with 'x'. Click 'Pipelines' in main menu discarding changes. The list of pipelines conatins two pipelines with identical names.

**Comment by skrchnavy** [comment]
related to UnifiedViews/Core#252

**Comment by mvi-eea-sk** [comment]
@OskarStoffan please test if it's still valid in UV 2.0.0
in the issue mentioned above, the name of pipeline was set to be a unique constraint in DB, so it shouldn't be possible to create pipe with name already used

**Comment by skrchnavy** [comment]
@OskarStoffan please test

**Comment by OskarStoffan** [comment]
When existing name of the pipeline is entered in the IC dialog the following error message is displayed (pipeline is not created in UV). So this is correct regarding UV behavior, but the error message is incorrect.

![bug3](https://cloud.githubusercontent.com/assets/8984799/7607529/606e3afa-f962-11e4-92d1-47c289e4cf4d.png)

**Comment by skrchnavy** [comment]
dependent issue UnifiedViews/Core#252 closed
