### ISSUE TITLE
When the name of the pipeline exceeds 1024 characters in IC, wrong error message is shown 

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/ckanext-odn-pipeline#4]
To create a new associated pipeline for a dataset choose 'Create new manually' from the combo box. Fill the name of the pipeline with string exceeding 1024 characters. The error message says: "Couldn't create/associate pipeline, probably UnifiedViews is not responding." Should be: "Error creating pipeline.  Max length is 1024 characters. Current length is xxx characters." (the same error message as in UV).

**Comment by skrchnavy** [comment]
@OskarStoffan to test is done in ODN 1.0.1

**Comment by OskarStoffan** [comment]
The problem persists.

![bug2](https://cloud.githubusercontent.com/assets/8984799/7606661/321d5d0e-f95b-11e4-8623-8a757393d6cc.png)

**Comment by mvi-eea-sk** [comment]
should be fixed in the same release as:
- https://github.com/UnifiedViews/Core/pull/439
- https://github.com/OpenDataNode/open-data-node/issues/131

@skrchnavy so shouldn't be milestone set ODNv_1.2.0 ?
