### ISSUE TITLE
Long names of pipelines are not editable/readable in IC and UV

### ISSUE THREAD

**Issue by OskarStoffan** [OpenDataNode/ckanext-odn-pipeline#5]
When a pipeline is created with long name: 
- it is not possible to see the whole name in the list of associated pipelines in IC
- it is not possible to modify the name in UV since the expand button is not visible

**Comment by skrchnavy** [comment]
@OskarStoffan to test is done in ODN 1.0.1

**Comment by OskarStoffan** [comment]
In UV the problem persists. 
In IC scrollbar is added (the name is readable), but the layout is visually unacceptable.

![bug](https://cloud.githubusercontent.com/assets/8984799/7606611/b2476822-f95a-11e4-985d-42fab4e6a02b.png)

**Comment by mvi-eea-sk** [comment]
fixed: only the catalog side

**Comment by mvi-eea-sk** [comment]
UV side fix waiting for:
https://github.com/UnifiedViews/Core/pull/438

**Comment by skrchnavy** [comment]
UnifiedViews/Core#438 merged into develop and released as version UV_Core_2.1.1
@mvi-eea-sk  can we close this issue?

**Comment by mvi-eea-sk** [comment]
@skrchnavy you can close this
