### ISSUE TITLE
to create resource readable name  

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/ckanext-odn-pipeline#8]
Let have a pipeline:

```
Extractor--------->T-Zipper------------>L-filesToLocalhost----->L-catalog--->CKAN
configuration: (it-x16/it-x16.zip)---->/var/www/dump---------(not important)---->Ckan 
final resources:name=it-x16/it-x16.zip,url=server/www/dump/it-x16/it-x16.zip
```

But Ckan resource:name should be resources:name=**readable resource name** and not  resources:name=**it-x16/it-x16.zip**

**Comment by mvi-eea-sk** [comment]
This is example JSON sent by L-Catalog to CKAN api:

``` JSON

{
    "pipelineId": 8,
    "resources": [
        {
            "storageId": {
                "type": "RDF",
                "value": "storageID"
            },
            "resource": {
                "name": "resource name",
                "description": "description of resource",
                "last_modified" : "2014-12-05 08:38:44.019000",
            }
        }
    ]
}
```

The resource name is set by L-Catalog and it isn't edited by the api call at all. That means it's L-Catalog responsibility to set it correctly.

**Comment by Jan-Marcek** [comment]
Ckan resource has the fields: name and url.

url: is generated from JSON's name. 
name: is copied from JSON's name. 
(Am I right?)

Let's have a readable_name != name_of_file then it won't correctly work.

**Comment by skrchnavy** [comment]
@Jan-Marcek / @mvi-eea-sk : this has to be discussed due to expected changes in communication from UV to CKAN (using DCAT format)

**Comment by mvi-eea-sk** [comment]
url is generated from sthe storageId part of JSON:

``` JSON
"storageId": {
    "type": "RDF",
    "value": "storageID"
}
```

if type is RDF, it uses the property odn.storage.rdf.uri.template (while replacing the placeholder)
if type == FILE -> odn.storage.file.uri.template

there are two fields in the resource parameters that can be given:
- name (required) - name of the resource, should be unique, i think UV uses here the virtual path variable here
- title (optional) - human readable name

**Comment by skrchnavy** [comment]
@mvi-eea-sk / @mkl-eea-sk - is this issue relevant for ODN 1.0.1 and newer (using L-*ToCKAN DPUs)?
